---
version: "3"
services:
  list:
    container_name: openstack-resource-manager
    build: .
    volumes:
      - ./clouds.yml:/etc/openstack/clouds.yml:ro
      - ./secure.yml:/etc/openstack/secure.yml:ro
